# Generated by Django 5.1.3 on 2024-12-15 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtyestateapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
