# Generated by Django 5.1.3 on 2024-12-15 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_alter_ticketcategories_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animals',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.ticketcategories', verbose_name='Категория'),
        ),
    ]
